"""add_wrestler_alter_egos

Revision ID: 41fd3d6cdfb0
Revises: de34c4501ffc
Create Date: 2026-02-13 08:12:33.671132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41fd3d6cdfb0'
down_revision: Union[str, Sequence[str], None] = 'de34c4501ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wrestlers', sa.Column('alter_egos', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wrestlers', 'alter_egos')
    # ### end Alembic commands ###
