"""add_wrestler_profile_columns

Revision ID: de34c4501ffc
Revises: 7821593ad505
Create Date: 2026-02-13 06:57:38.532218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de34c4501ffc'
down_revision: Union[str, Sequence[str], None] = '7821593ad505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wrestlers', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('wrestlers', sa.Column('birth_place', sa.String(), nullable=True))
    op.add_column('wrestlers', sa.Column('height', sa.String(), nullable=True))
    op.add_column('wrestlers', sa.Column('weight', sa.String(), nullable=True))
    op.add_column('wrestlers', sa.Column('style', sa.String(), nullable=True))
    op.add_column('wrestlers', sa.Column('debut', sa.String(), nullable=True))
    op.add_column('wrestlers', sa.Column('roles', sa.String(), nullable=True))
    op.add_column('wrestlers', sa.Column('nicknames', sa.String(), nullable=True))
    op.add_column('wrestlers', sa.Column('signature_moves', sa.String(), nullable=True))
    op.add_column('wrestlers', sa.Column('trainers', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wrestlers', 'trainers')
    op.drop_column('wrestlers', 'signature_moves')
    op.drop_column('wrestlers', 'nicknames')
    op.drop_column('wrestlers', 'roles')
    op.drop_column('wrestlers', 'debut')
    op.drop_column('wrestlers', 'style')
    op.drop_column('wrestlers', 'weight')
    op.drop_column('wrestlers', 'height')
    op.drop_column('wrestlers', 'birth_place')
    op.drop_column('wrestlers', 'birth_date')
    # ### end Alembic commands ###
